name: CMake Build

env:
  CMAKE_VERSION: 3.20.1

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Ubuntu bundled build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install OpenCV
      run: |
        sudo apt install libopencv-dev

    - name: Build
      run: |
        cd cpp
        cmake .
        make
